# Goal
geometry_msgs/Point position
geometry_msgs/Vector3 orientation
string frame
float64 speed_ratio
float64 finger_width
---
# Result
bool success
string message
float64[7] final_joint_angles
float64[6] final_tcp_pose
---
# Feedback
float64 progress
float64[7] current_joint_angles
float64 estimated_time_remaining
